sudo: true

language: java

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

git:
  depth: 99999

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

services:
- docker

before_install:
- docker exec -i mysql mysql -uroot -padmin  <<< "create database test_bank;"
- docker run -d -p 127.0.0.1:80:4567 gradle:jdk8

install: true

jobs:
  include:
  - stage: executing tests
    script:
    - ./gradlew clean test